{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "active_users_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "active users"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "rate(auth_attempts_successful_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Successful"
    },
    {
     "expr": "rate(auth_attempts_failed_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "rate(total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(get_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(post_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(delete_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(put_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "cpu_percent"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "request_duration_milliseconds_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "request duration"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(pizzas_purchases_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "pizza purchases"
    },
    {
     "expr": "rate(creation_failures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "purchase failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 22 },
   "targets": [
    {
     "expr": "rate(revenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "revenue"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 22 },
   "targets": [
    {
     "expr": "creation_latency_milliseconds_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "creation latency"
    }
   ]
  }
 ]
}